/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Irm__factory } from './Irm__factory';
export { Morpho__factory } from './Morpho__factory';
export { Oracle__factory } from './Oracle__factory';
export { PriceFeed__factory } from './PriceFeed__factory';
